#!/bin/bash

# Check if the script is being run as root or if the user has sudo privileges
if [ "$(id -u)" -ne 0 ]; then
    # Check if the user can run sudo without a password prompt (to prevent asking for sudo password early in the script)
    if ! sudo -v &>/dev/null; then
        echo "This script requires root or sudo privileges to run apt."
        exit 1
    fi
fi

echo "Installing git and github helper..."

sudo apt-get install git -y > /dev/null
sudo apt-get install gh -y > /dev/null

echo "Follow the github helper prompts..."
gh auth login --web
gh config set git_protocol https -h github.com
gh auth setup-git

git config --global user.name "UK-Jimbo"
git config --global user.email "126205015+UK-Jimbo@users.noreply.github.com"
git config --global init.defaultBranch main

echo "Github helper installed and configured."